// <auto-generated />
namespace NashGaming.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class June2_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(June2_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201606022030348_June2_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
